package sc.android.wishlistapp.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "wish_table")   //creates table and each variable of data class is a column and each object is a row
data class Wish(
    @PrimaryKey(autoGenerate = true)    //set as primary key which is autogenerated (even if items are deleted)
    val id : Long = 0L,
    @ColumnInfo(name = "wish_title")    //column name
    val title : String = "",
    @ColumnInfo(name = "wish_desc")     //column name
    val description : String = ""
)
